# Site settings
title: Liang Ke Jin
description: Liang Ke Jin
favicon: /assets/img/avatar.JPG
baseurl:
url: https://liungkejin.github.io
rss_url:

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlight: true
timezone: Asia/Shanghai

# exclude: [vendor]

# paginate: 5
# paginate_path: "blog/page:num"
